Dealing with too much logMessages in CSC detailed view
lsst-ts/LOVE-frontend pull request #332
Opened 2021-11-04 19:59 UTC by fdelcampo

Set a slice for the arrays logMessageData and errorCodeData

2021-11-04 20:39 UTC, sebastian-aranda requested changes
Thanks @fdelcampo , I only left a comment regarding a console.log

2021-11-04 20:39 UTC, sebastian-aranda commented on love/src/components/EventLog/EventLog.container.jsx
> +    //console.log(realm);
This should be removed

2021-11-05 15:13 UTC, fdelcampo commented on love/src/components/EventLog/EventLog.container.jsx
> +    //console.log(realm);
yes, in other commit

2021-12-20 19:21 UTC, sebastian-aranda approved these changes
Thanks @fdelcampo this is ready to be merged

2021-12-21 17:59 UTC, merged