TMA Implementation
lsst-ts/LOVE-frontend pull request #352
Opened 2022-02-24 19:31 UTC by fdelcampo

2022-02-24 21:09 UTC, sebastian-aranda requested changes
Great job here Fernando! I some comments regarding some details, there rest looks very good

2022-02-24 21:09 UTC, sebastian-aranda commented on love/src/components/MainTel/TMA/MirrorCovers/MirrorCovers.jsx
> +    /** Mirror Covers view width */
Good job 👍️

2022-02-24 21:09 UTC, sebastian-aranda commented on love/src/components/MainTel/TMA/Elevation/Elevation.jsx
> +    const { width, height } = this.props;
I think this variables are not called anywere so they should be removed

2022-02-24 21:50 UTC, fdelcampo commented on love/src/Config.js
> +// TODO: Pending Style
Yes, need validation about the colors used for the states.
@MiaRoseElbo

2022-02-24 21:54 UTC, fdelcampo commented on love/src/redux/selectors/selectors.js
> +      ? summaryData['event-MTMount-0-elevationSystemState'][0].state.value
thanks

2022-02-24 22:16 UTC, fdelcampo commented on love/src/redux/selectors/selectors.js
> +    balancing: summaryData['event-MTMount-0-commander']
thanks

2022-02-24 22:23 UTC, fdelcampo commented on love/src/components/MainTel/TMA/TMA.module.css
> +    /* background: #132631; svg color, slightly better contrast with background */
yes, for the table, its not necessary. padding and border yes

2022-02-24 22:35 UTC, fdelcampo commented on love/src/components/MainTel/TMA/MirrorCovers/MirrorCovers.jsx
> +      this.prevAzimuthDemand = this.closestEquivalentAngle(this.prevAzimuthDemand, prevProps.azimuthDemandPosition);
OK, Its changed

2022-02-24 22:38 UTC, fdelcampo commented on love/src/components/MainTel/TMA/MirrorCovers/MirrorCovers.jsx
> +    const equivalentAzimuthDemand = this.closestEquivalentAngle(this.prevAzimuthDemand, this.props.azimuthDemandPosition);
Ok, its changed

2022-03-02 21:13 UTC, areyesd14 commented on love/src/components/MainTel/TMA/Summary/Summary.jsx
> +        const azimuthLimits = this.azimuthLimits ? this.azimuthLimits : 0;
is this resolved?

2022-03-02 21:14 UTC, areyesd14 commented on love/src/components/MainTel/TMA/Summary/Summary.jsx
> +        // const closestAzimuthLimit = 90;
I think this is unresolved.

2022-03-02 21:14 UTC, areyesd14 commented on love/src/components/MainTel/TMA/Summary/Summary.jsx
> +        const elevationLimits = this.elevationLimits ? this.elevationLimits : 0;
I think this is unresolved.

2022-03-02 21:17 UTC, areyesd14 approved these changes
If all Sebastian comments were resolved, I approve this PR. Excellent job @fdelcampo !!

2022-07-13 15:32 UTC, sebastian-aranda approved these changes
Everything looks good and ready for merge! Great job @fdelcampo

2022-07-13 16:13 UTC, merged