Tickets/dm 34255
lsst-ts/LOVE-frontend pull request #358
Opened 2022-04-06 04:00 UTC by tribeiro

This PR add 3 updates:
1 - Changes how the heartbeat message is handled in the `CSCDetail` view. It allows us to differentiate between the condition when there is not heartbeat from the producer (producer is not running), the producer does not receive a heartbeat from the CSC or the heartbeat from the producer is stale.
2 - Add the CSC version to the `CSCExpanded` view.
3 - Add the capability to send summary state commands (`start`, `enable`, `disable` and `standby`) from the `CSCExpanded` view as well as selecting a configuration for the `start` command when the CSC has options available.

2022-04-06 15:34 UTC, sebastian-aranda requested changes
Nice job! I've left some minor comments. Thanks @tribeiro !

2022-04-07 18:07 UTC, tribeiro commented on love/src/components/CSCSummary/CSCExpanded/CSCExpanded.container.jsx
>      summaryStateData: summaryStateData[0],
good idea!

2022-04-07 18:29 UTC, tribeiro commented on love/src/components/CSCSummary/CSCExpanded/CSCExpanded.jsx
> +import 'react-dropdown/style.css';
oh wow! this is really nice! Thanks for the suggestion!

2022-04-07 18:30 UTC, tribeiro commented on love/src/components/CSCSummary/CSCExpanded/CSCExpanded.jsx
> +    let configurationOverride = this.state.configurationOverride;
nice! thanks!

2022-04-07 21:21 UTC, merged