Implementation WeatherForecast
lsst-ts/LOVE-frontend pull request #468
Opened 2023-05-24 15:35 UTC by fdelcampo

2023-05-29 17:01 UTC, sebastian-aranda requested changes
Great job @fdelcampo ! I really appreciate you improved and refactored several things. I left comments regarding code quality and a few suggestion, please take a look to them 🙏️

2023-05-31 19:45 UTC, fdelcampo commented on love/src/components/icons/Weather/CloudInSkyIcon/CloudInSkyIcon.jsx
In this moment not used with a refactor. This file removed

2023-06-15 18:13 UTC, fdelcampo commented on love/src/components/GeneralPurpose/Plot/TimeSeriesControls/TimeSeriesControls.jsx
> +          />
It's necessary for the actual comportament, the negation operation

2023-06-15 19:41 UTC, sebastian-aranda approved these changes
Looks good to be merged :+1:

2023-06-15 19:47 UTC, fdelcampo commented on love/src/components/WeatherStation/CurrentValues/CurrentValues.jsx
> +    currentWindSpeedUnits: undefined,
In the case that is `undefined`, the text is `'-'` and not a `'number °C'`, for example

2023-06-15 20:00 UTC, merged