Microphones Component implementation
lsst-ts/LOVE-frontend pull request #471
Opened 2023-06-02 19:10 UTC by fdelcampo

2023-06-02 21:19 UTC, sebastian-aranda requested changes
Great job @fdelcampo, thanks! I've left some comments, please check those out 🙏️.

2023-06-02 21:19 UTC, sebastian-aranda commented on love/src/components/Mics/Table/Row.jsx
> +    }
You should use the following setState form here instead:
```javascript
this.setState((prevState) => {
  if (!prevState.isSelected) {
    return { isSelected: true, alarm: false };
  }
  else {
    return { isSelected: false };
  }
});
```

2023-06-02 21:19 UTC, sebastian-aranda commented on love/src/components/Mics/Table/Row.jsx
> +    else this.setState({ notifications: true });
You should use the following setState form here instead:
```javascript
this.setState((prevState) => {
  if (prevState.notifications) {
    return { notifications: false, alarm: false };
  }
  else {
    return { notifications: true };
  }
});
```

2023-06-02 21:19 UTC, sebastian-aranda commented on love/src/components/Mics/Table/Table.jsx
> +    initialPlaying: PropTypes.bool,
Please add a description for the `initialPlaying` propType 🙏️.

2023-06-02 21:19 UTC, sebastian-aranda requested changes
Great job @fdelcampo, thanks! I've left some comments, please check those out 🙏️.

2023-06-09 17:15 UTC, fdelcampo commented on love/src/components/Mics/Details/DrawerMic.jsx
> +    maxHeight: PropTypes.number,
Removed maxHeight prop. Not necessary the definition

2023-06-09 17:39 UTC, fdelcampo commented on love/src/components/Mics/Details/HeatMap/HeatMap.jsx
> +        {/* <div className={styles.divVegaLite}> */}
removed

2023-06-09 19:32 UTC, sebastian-aranda approved these changes
Great job @fdelcampo, I love how the component ended! Thanks for reviewing the feedback, go ahead with the merge 👍️.

2023-06-09 19:32 UTC, sebastian-aranda commented
You will need a rebase.

2023-06-12 19:20 UTC, merged